# Generated by Django 2.0.6 on 2019-07-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
