# Generated by Django 2.0.6 on 2019-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_signup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='otpgentime',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
