# Generated by Django 2.0.6 on 2019-07-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_auto_20190713_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
