# Generated by Django 2.0.6 on 2019-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0010_signup_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='token',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
